# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- publish: $(System.DefaultWorkingDirectory)
- task: Veracode@2
  inputs:
    ConnectionDetailsSelection: 'Credentials'
    username: 'f2d521a7b36f191e0d97daaa0efe1a7b'
    password: 'e386ce7ca48b66742111f5645de7cd365aec028237ac8956e5156c34e4a335da3c12a00bd1a6916ef90d707eb34a013c7512349f6f695afd7fc9e79e15a5c33e'
    veracodeAppProfile: 'Ian CircleCI Test App'
    version: '$(build.buildNumber)'
    filepath: '$(System.DefaultWorkingDirectory)'
    createSandBox: false
    createProfile: false
    failTheBuildIfVeracodeScanDidNotInitiate: false
    scanStatusCheckInterval: '60'
    importResults: true
    failBuildOnPolicyFail: false